modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/camera/issues"
[[mods]]
modId = "camera"
version = "${mod_version}"
displayName = "Camera Mod"
updateJSONURL = "https://update.maxhenkel.de/forge/camera"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/camera-mod"
authors = "Max Henkel"
description = '''This mod adds a working camera'''
[[dependencies.camera]]
modId = "forge"
mandatory = true
versionRange = "${forge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.camera]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.camera]]
modId = "jei"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.camera]]
modId = "jade"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"